### ISSUE TITLE
Missing a note that this is a mirror

### ISSUE THREAD

**Issue by Hi-Angel** [nawawi/klish#3]
I was puzzled that main site mentions some releases, however this repo has no branches/tags and the page "Releases" is empty. Well, where are they? Turns out it is because the upstream repo is here https://src.libcode.org/pkun/klish and it does have branches for releases. The github repo is just a mirror. Would be useful to mention that in the repository description.

**Comment by Hi-Angel** [comment]
Alright, nvm, it turns out the site has no way to get registered, it is apparently someone's personal site. That's probably the reason this repo is here.

**Comment by nawawi** [comment]
yes, this is mirror.. for my personal backup.. will put some description.. thanks.
